# Generated by Django 3.1.7 on 2021-03-03 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('is_waiting', models.BooleanField(default=False, verbose_name='来院受付済み')),
            ],
        ),
        migrations.CreateModel(
            name='Shouhin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='価格')),
            ],
        ),
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shouhin_number', models.IntegerField(default=1, verbose_name='個数')),
                ('shouhin_total_price', models.IntegerField(verbose_name='合計')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kaikei.customer', verbose_name='顧客')),
                ('shouhin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kaikei.shouhin', verbose_name='商品')),
            ],
        ),
    ]
